config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'

  get 'welcome/home'

  get '/visits/:id' => 'visits#index', as: :visit

  post 'visits' => 'visits#create'

  devise_for :users
  
  resources :customers do
    resources :pets do 
      resources :visits
    end
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	belongs_to :veterinary
	has_many :pets, dependent: :destroy

	validates :name, :email, :phone, presence: true
	
end

app/models/pet.rb
class Pet < ActiveRecord::Base
	belongs_to :veterinary
	belongs_to :customer
	has_many :visits
	validates :name, :breed, presence: true
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :veterinary
  validates :veterinary, presence: true
end

app/models/veterinary.rb
class Veterinary < ActiveRecord::Base
  has_many :users
  has_many :pets
  has_many :customers

  validates :name, presence: true
  
end

app/models/visit.rb
class Visit < ActiveRecord::Base
	belongs_to :pet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!, except: [:home]

  before_action :set_veterinary

  def after_sign_in_path_for(resource)
    customers_path || stored_location_for(resource) || root_path
  end

  protected
  def set_veterinary

  	@veterinary = current_user.veterinary if current_user

  end

  before_action :set_locale
 
	def set_locale
  		I18n.locale = extract_locale_from_tld || I18n.default_locale
	end

	def extract_locale_from_tld
  		parsed_locale = request.host.split('.').last
  		I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
	end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = @veterinary.customers
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @pet = Pet.new
  end

  # GET /customers/new
  def new
    @customer = Customer.new
    @customer_user = current_user
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)
    @customer.veterinary = @veterinary
    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Cliente creado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Cliente actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Cliente eliminado con éxito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = @veterinary.customers.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :email, :phone)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
    @visit = Visit.new
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @customer = @veterinary.customers.find params[:customer_id]
    @pet = Pet.new(pet_params)
    @pet.veterinary = @veterinary
    @pet.customer = @customer

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @customer, notice: 'Registro de mascota exitoso.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :breed, :age)
    end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
	def index 
  		@visits = Visit.all  
	end

	def new 
  		@visit = Visit.new 
	end

	def create 
	  @visit = Visit.new(visit_params) 
	  @visit.pet = @pet
	  respond_to do |format|
	  	if @visit.save 
	  	  format.html { redirect_to @visit, notice: 'Registro de visita exitoso.' }
          format.json { render :index, status: :created, location: @visit } 
	  	else 
	      format.html { render :new }
          format.json { render json: @visit.errors, status: :unprocessable_entity } 
		end
	end
end

private 
	def visit_params 
	    params.require(:visit).permit(:content) 
	end

	def show 
	  @pet = Pet.find(params[:id]) 
	  @visits = @pet.visits 
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
  	flash[:notice] = t(:hello_flash)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<section class="customers">
	<body>
	  <h1>Editar cliente</h1>
	  <div role="main" class="main-content">
		<div class="autoform" id="login-edit">
			<%= render 'form' %>
			<%= link_to 'Ver detalle', @customer, class: "btn btn-primary" %> |
			<%= link_to 'Regresar', customers_path, class: "btn btn-primary" %>
		</div>
  	  </div>
  	</body>
</section>

app/views/customers/index.html.erb
<section class="customers">
  <div class="container">
    <div class="customer-index">
      <p id="notice"><%= notice %></p>
      <h1>Lista de clientes</h1>
      <br>
      <%= link_to 'Nuevo Cliente', new_customer_path, class:"btn btn-primary" %>
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Nombre</th>
                <th>Correo Electrónico</th>
                <th>Teléfono</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @customers.each do |customer| %>
                <tr>
                  <td><%= customer.name %></td>
                  <td><%= customer.email %></td>
                  <td><%= customer.phone %></td>
                  <td><%= link_to 'Ver detalle', customer %></td>
                  <td><%= link_to 'Editar', edit_customer_path(customer) %></td>
                  <td><%= link_to 'Borrar', customer, method: :delete, data: { confirm: '¿Estás seguro de eliminar al cliente, se eliminarán todos sus datos?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
    </div>
  </div>
</section>

app/views/customers/new.html.erb
<section class="customers">
  <body>
  	<h1>Registra a un cliente nuevo</h1>
  	  <div role="main" class="main-content">
		<div class="autoform" id="login-edit">
		<%= render 'form' %>
		<%= link_to 'Regresar', customers_path, class: "btn btn-primary" %>
		<p>* Todos los campos son obligatorios *</p>
		</div>
  	  </div>
  </body>
</section>

app/views/customers/show.html.erb
<section class="customers">
  <div class="container">
    <div class="customer-show">
      <h1>Detalle de cliente</h1>
      <p id="notice"><%= notice %></p>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Correo electrónico</th>
              <th>Teléfono</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @customer.name %></td>
              <td><%= @customer.email %></td>
              <td><%= @customer.phone %></td>
              <td><%= link_to 'Editar', edit_customer_path(@customer), class:"btn btn-primary" %></td>
              <td><%= link_to 'Regresar', customers_path, class:"btn btn-primary" %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <h1>Registro de mascota </h1>
      <%= render "pets/form" %>
      <div class="table-responsive">
        <table class="table table-striped ">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Raza</th>
              <th>Edad</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @customer.pets.each do |pet| %>
              <tr>
                <td><%= pet.name %></td>
                <td><%= pet.breed %></td>
                <td><%= pet.age %></td>
                <td><%= link_to 'Ver visitas', visit_path %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
  <title>Mi Veterinaria</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="shortcut icon" <%= image_tag 'favicon.ico' %>
  <link href='https://fonts.googleapis.com/css?family=Play' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Happy+Monkey' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Sniglet' rel='stylesheet' type='text/css'>
  <link href="http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>

</head>
<body>
<header>
<% if current_user %>
  <nav class="navbar navbar-fixed-top " role="navigation">
    <div class="container">
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="top-navbar-1">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>Bienvenido &nbsp;<%= current_user.name %></li><br/>
            <li><%= current_user.veterinary.name %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <form class="navbar-form navbar-left" role="search">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
              </div>
              <button type="submit" class="btn btn-primary">Buscar</button>
            </form>
            <% if user_signed_in? %>
              <li><button type="button" class="btn btn-danger"><%= link_to "Salir", destroy_user_session_path, method: :delete %></button></li>
            <% else %>
              <li><button type="button" class="btn btn-primary"><%= link_to "Entrar", new_user_session_path %></button></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </div>
  </nav>
<% end %>
</header>

<%= yield %>

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <ul class="legals">
            <li><a href="#">Términos y condiciones</a></li>
            <li><a href="#">Aviso de privacidad</a></li>
          </ul>
        </div>
        <div class="col-md-6 credit">
          <p>Realizado por <a href="#">ebm-proyect</a></p>
        </div>
      </div>
    </div>
  </footer>

</body>
</html>

app/views/pets/_form.html.erb
<%= form_for([@customer, @pet]) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<form class="form-inline">
  <div class="field form-group table-show">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :breed %>
    <%= f.text_field :breed %>
    <%= f.label :age %>
    <%= f.text_field :age %>
    <%= f.submit class:"btn btn-primary btn-show" %>
  </div>
<% end %>
</form>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Breed</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.breed %></td>
        <td><%= pet.age %></td>
        <td><%= link_to 'Ver detalles', pet %></td>
        <td><%= link_to 'Editar', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo registro', new_pet_path %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @pet.breed %>
</p>

<p>
  <strong>Age:</strong>
  <%= @pet.age %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>

app/views/visits/_form.html.erb
<%= form_for(@visit) do |f| %> 
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this customer from being saved:</h2>
        <ul>
        <% @visit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
    </div>
<% end %> 

  <div class="field"> 
    <%= f.label :title %><br> 
    <%= f.text_field :title %> 
  </div> 
  <div class="field"> 
    <%= f.label :observation %><br> 
    <%= f.text_area :observation %> 
  </div>
  <div class="actions"> 
    <%= f.submit "Guardar", class:"btn btn-primary" %></br>
    <%= link_to 'Regresar', visit_path(:id), class:"btn btn-primary" %>
  </div> 
<% end %>    

app/views/visits/index.html.erb
<section class="customers">
  <div class="container">
    <div class="customer-show">
    	<h1>Lista de Visitas</h1>
    	<p id="notice"><%= notice %></p>
    	<td><%= link_to 'Nueva visita', new_customer_pet_visit_path(:customer_id, :pet_id), class:"btn btn-primary" %></td>
    	<td><%= link_to 'Regresar', customers_path, class:"btn btn-primary" %></td>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
          	<tr>
		      <th>Titulo</th>
		      <th>Observaciones</th>
		      <th>Fecha</th>
		      <th colspan="3"></th>
		    </tr>
  		  </thead>
		  <tbody> 
		    <% @visits.each do |visit| %>
		      <tr>
		        <td><%= visit.title %></td>
		        <td><%= visit.observation %></td>
		        <td><%= visit.created_at %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
	  </div>
	</div>
  </div>
</section>

app/views/visits/new.html.erb
<section class="visits">
  <body>
  	<h1>Registra una visita nueva</h1>
  	  <div role="main" class="main-content">
		<div class="autoform" id="login-edit">
    		 <%= render 'visits/form' %>
    		<p>* Todos los campos son obligatorios *</p>
		    </div>
  	  </div>
  </body>
</section>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @pet.visits %>
</p>

<p>
  <strong>Created at:</strong>
  
</p>

app/views/welcome/home.html.erb
<!-- Top menu -->
<nav class="navbar navbar-fixed-top " role="navigation">
  <div class="container">
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="top-navbar-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><%= link_to "Inicio", root_path %><span class="sr-only">(current)</span></li>
        <li><a class="scroll-link" href="#responsive">¿Quiénes somos?</a></li>
        <li><a class="scroll-link" href="#intro">Nuestros servicios</a></li>
        <li><a class="scroll-link" href="#contact">Contacto</a></li>
          <% if user_signed_in? %>
            <li><%= current_user.veterinary.name %></li>
            <li><%= current_user.email %></li>
            <li><%= link_to "Salir", destroy_user_session_path, method: :delete %></li>
          <% else %>
              <li><%= link_to "Entrar", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
    
    <section class="hero swag1" id="hero">
            <div class="container ">
              <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center inner">
                  <h1 class="animated fadeInDown">Mi <span>Veterinaria</span></h1>
                  <p class="animated fadeInUp delay-05s">Un sistema de administración eficaz para <em>clínicas veterinarias.</em></p>
                </div>
              </div>
            </div>
          </section>
        

        <section class="text-center swag3" id="responsive">
          <div class="container-fluid nopadding responsive-services">
            <div class="wrapper">
              <div class="iphone">
                <div class="wp3 animated fadeInDown"></div>
              </div>
              <div class="fluid-white"></div>
            </div>
            <div class="container designs">
              <div class="row">
                <div class="col-md-5 col-md-offset-7">
                  <div id="servicesSlider">
                    <div class"flex-viewport">
                      <ul class="slides">
                        <li class="clone">
                          <h1 class="arrowS">¿Quiénes somos?</h1>
                          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ultricies nulla non metus pulvinar imperdiet. Praesent non adipiscing libero. </p>
                          <p>
                          Mauris ultrices odio vitae nulla ultrices iaculis. Nulla rhoncus odio eu lectus faucibus facilisis. Maecenas ornare augue vitae sollicitudin accumsan. </p>
                          <p>Etiam eget libero et erat eleifend consectetur a nec lectus. Sed id tellus lorem. Suspendisse sed venenatis odio, quis lobortis eros.</p>
                        </li>
                        <li>
                          <h1 class="arrowS">Bootstrap Professionals</h1>
                          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ultricies nulla non metus pulvinar imperdiet. Praesent non adipiscing libero. </p>
                          <p>
                          Mauris ultrices odio vitae nulla ultrices iaculis. Nulla rhoncus odio eu lectus faucibus facilisis. Maecenas ornare augue vitae sollicitudin accumsan. </p>
                          <p>Etiam eget libero et erat eleifend consectetur a nec lectus. Sed id tellus lorem. Suspendisse sed venenatis odio, quis lobortis eros.</p>
                        </li>
                      </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section class="intro text-center section-padding swag4" id="intro">
          <div class="container">
            <div class="row">
              <div class="col-md-8 col-md-offset-2 ">
                <h1 class="arrow">Nuestros servicios</h1>
                <p>Sed a lorem quis neque interdum consequat ut sed sem. Duis quis tempor nunc. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent id tempor ipsum. Fusce at massa ac nunc porta fringilla sed eget neque. Quisque quis pretium nulla. Fusce eget bibendum neque, vel volutpat augue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>
              </div>
            </div>
          </div>
        </section>

        <section class="features text-center section-padding swag4" id="features">
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <h1 class="arrowS">Tenemos la solución, para una buena administración de tu negocio</h1>
                <div class="features-wrapper">
                  <div class="col-md-4 ">
                    <div class="icon">
                      <i class="fa fa-laptop shadow"></i>
                    </div>
                    <h2>Acceso 24/7</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a lorem quis neque interdum consequat ut sed sem. Duis quis tempor nunc. Interdum et malesuada fames ac ante ipsum
                    primis in faucibus.</p>
                  </div>
                  <div class="col-md-4 delay-05s">
                    <div class="icon">
                      <i class="fa fa-code shadow"></i>
                    </div>
                    <h2>Soporte Técnico</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a lorem quis neque interdum consequat ut sed sem. Duis quis tempor nunc. Interdum et malesuada fames ac ante ipsum
                    primis in faucibus.</p>
                  </div>
                  <div class="col-md-4 delay-1s">
                    <div class="icon">
                      <i class="fa fa-heart shadow"></i>
                    </div>
                    <h2>Creatividad</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a lorem quis neque interdum consequat ut sed sem. Duis quis tempor nunc. Interdum et malesuada fames ac ante ipsum
                    primis in faucibus.</p>
                  </div>
                  
              </div>
            </div>
          </div>
        </section>

        
        <section class="swag text-center">
          <div class="container">
            <div class="row">
              <div class="col-md-8 col-md-offset-2">
                <h1>La administración del negocio es mucho trabajo?<span>nosotros <em>tenemos</em> la solución perfecta</span></h1>
              </div>
            </div>
          </div>
        
        
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <p class="ignite-btn">¡ Entendemos tu pasión !</p>
              </div>
            </div>
          </div>
        
        </section>
        
        <div class="row swag" id="contact">
        <div class="col-sm-6 contact-form fadeInUp">
                      <h3>Necesitas información? Escríbenos:</h3>
                      <form role="form" action="#" method="post">
                        <div class="form-group">
                          <label class="sr-only" for="contact-email">Correo Electrónico</label>
                            <input type="text" name="email" placeholder="Email..." class="contact-email form-control" id="contact-email">
                          </div>
                          <div class="form-group">
                            <label class="sr-only" for="contact-subject">Asunto</label>
                            <input type="text" name="subject" placeholder="Asunto..." class="contact-subject form-control" id="contact-subject">
                          </div>
                          <div class="form-group">
                            <label class="sr-only" for="contact-message">Mensaje</label>
                            <textarea name="message" placeholder="Mensaje..." class="contact-message form-control" id="contact-message"></textarea>
                          </div>
                          <button type="submit" class="btn btn-primary">Enviar</button>
                      </form>
                  </div>
              </div>
              
              
        <section class="dark-bg text-center section-padding contact-wrap" id="contact">
          <a href="#top" class="up-btn" ><i class="fa fa-chevron-up"></i></a>
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <h1 class="arrow">Contacto</h1>
              </div>
            </div>
            <div class="row contact-details">
              <div class="col-md-4">
                <div class="light-box box-hover">
                  <h2><i class="fa fa-map-marker"></i><span>Oficinas</span></h2>
                  <p>CDMX</p>
                </div>
              </div>
              <div class="col-md-4">
                <div class="light-box box-hover">
                  <h2><i class="fa fa-mobile"></i><span>Teléfono</span></h2>
                  <p>+52 55 5555 5555</p>
                </div>
              </div>
              <div class="col-md-4">
                <div class="light-box box-hover">
                  <h2><i class="fa fa-paper-plane"></i><span>Correo electrónico</span></h2>
                  <p>info@ebm-proyect.com</p>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <ul class="social-buttons">
                  <!--<li><a href="#" class="social-btn"><i class="fa fa-dribbble"></i></a></li>
                  <li><a href="#" class="social-btn"><i class="fa fa-twitter"></i></a></li>
                  <li><a href="#" class="social-btn"><i class="fa fa-envelope"></i></a></li> -->
                </ul>
              </div>
            </div>
          </div>
        </section>
        